% function [] = rbr1050_process(gauge_ht,filter_time,Waves,nfft,time_start,time_end)% 
% 
% Process RBR pressure data
% Justin Rogers, Stanford EFML, September 2013
%
% This script loads .mat or .txt files generated by RBR pressure loggers
%
% input:
% gauge height = height of pressure sensor above bottom
% filter_time = time in minutes for desired low pass filtering
% Waves, if 1, process waves, if 0, no processing
% nfft = number of data points to use for wave averaging
% time_start = optional time to begin processing
% time_end = optional time to end processing
%

%%
function [] = sbe26_process(gauge_ht,filter_time,P_atm,Waves,...
    WavesBurst,nfft,fcutoff,time_start,time_end,yr)
g=9.81;
S=34.6;


TXT_files=dir('*.tid');
WAV_files = dir('*.rpt');
WB_files = dir('*.wb');

for ii=1:length(TXT_files)
    
    if ~isempty(TXT_files) % if txt file
        
        headerlines=0;
        filename=TXT_files(ii).name;
        DATA = importdata(filename,' ',headerlines);
        
        SBE.pressure = 6894.76*DATA.data(:,1)'; % convert psi to Pa
        SBE.temp = DATA.data(:,2)'; % deg C
        
        for i=1:size(DATA.textdata,1)
            SBE.mtime(i) = datenum([DATA.textdata{i,2} ' ' DATA.textdata{i,3}]);
        end
        if yr~=year(SBE.mtime(1))
            % correct year
            a = datevec(SBE.mtime); 
            a(:,1) = yr;
            SBE.mtime = datenum(a);
        end
        clear a
        
        SBE.dt_sec = nanmedian(diff(SBE.mtime))*3600*24;
        
    end
    
    if ~isempty(WAV_files) % if txt file
        
        headerlines=20;
        filename=WAV_files(ii).name;
        DATA = importdata(filename,' ',headerlines);
        
        
        SBE.Hsig = DATA.data(:,1)'/100; % sig wv ht, convert cm to m
        SBE.Tsig = DATA.data(:,2)'; % sig wv period (s)
        SBE.SSE = DATA.data(:,3:end)'/100^2; % wv energy (m^2)
        
        C = strsplit(DATA.textdata{18,1},' ');
        C2 = strsplit(C{1,4},'+');
        SBE.E_bins_s = str2double(C2{1,1});
        C = C(1,5:end);
        for i=1:length(C);
            SBE.E_bins_s=[SBE.E_bins_s str2double(C{1,i})];
        end
        SBE.E_bins_f = 1./SBE.E_bins_s;
     
        
        ig = headerlines-1;
        for i=1:length(SBE.Hsig)
            SBE.mtime_wave(i) = datenum([DATA.textdata{i+ig,1} ' ' DATA.textdata{i+ig,2}]);
        end
        if yr~=year(SBE.mtime_wave(1))
            % correct year
            a = datevec(SBE.mtime_wave); 
            a(:,1) = yr;
            SBE.mtime_wave = datenum(a);
        end
        clear a
        
        SBE.dt_wave_sec = nanmedian(diff(SBE.mtime_wave))*3600*24;
        
    end
    
    if ~isempty(WB_files)
        filename=WB_files(ii).name;
        headerlines=1;
        DATA = importdata(filename);
        
        type = DATA.textdata{1};
        % find index of headers
        indx = ~isnan(DATA.data(:,4));
        SBE.wave.no = DATA.data(indx,1);
        SBE.wave.time = DATA.data(indx,2);
        SBE.wave.sample_rate = DATA.data(indx,3);
        SBE.wave.samples = DATA.data(indx,4);
        
        if isfield(SBE,'mtime_wave')
            SBE.wave.mtime = SBE.mtime_wave';
        else
            if strcmp('SBE 26plus',type) % if sbe26+, sec since jan 1, 2000            
                SBE.wave.mtime = SBE.wave.time/24/3600+datenum(2000,1,1,0,0,0);          
            else % if sbe 26, sec since jan 1 1989
                SBE.wave.mtime = SBE.wave.time/24/3600+datenum(1989,1,1,0,0,0);
            end
            if yr~=year(SBE.wave.mtime(1))
                % correct year
                a = datevec(SBE.wave.mtime); 
                a(:,1) = yr;
                SBE.wave.mtime = datenum(a);
            end
        end
        clear a
        data = DATA.data(~indx,1:3);
        tdata = DATA.textdata(2:end,1);
        tdata = tdata(~indx);
        for i=1:length(tdata)
            tdata2(i) = str2num(tdata{i});
        end
        data = [tdata2' data];
        jj = SBE.wave.samples(1)/4;
        for i =1:length(SBE.wave.mtime)
            indx_end = jj*i;
            tdata = data((indx_end-jj+1):indx_end,:);
            SBE.wave.pressure(i,:) = 6894.76*reshape(tdata',1,[]);%convert psi to Pa
            
        end
    end
    
    clear MAT_files TXT_files DATA sec j jj press_Pa headerlines data...
        tdata tdata2 jj i indx
%% process data

    if isempty(P_atm) % if no manually defined atmospheric P
    % find avg atmospheric pressure within expected range 
    % (31.99 and 25.69)inHg = (108318, 86986) Pa
    %     indx = SBE.press_Pa_total < 108318 & SBE.press_Pa_total > 86986;
        indx = SBE.pressure < 1.06E5 & SBE.pressure > 86986;    
        P_atm = nanmedian(SBE.pressure(indx));
        if isempty(P_atm) || isnan(P_atm)
           P_atm = 1.01324997E5;
        end
    end   
    
    % find normalized pressure
    SBE.press_Pa = SBE.pressure-P_atm;
    SBE.wave.press_Pa = SBE.wave.pressure-P_atm;
    
    % find pressures outside 1 std of middle 1/2 of data set
    if isempty(time_start) % if no manual trim defined
        indx3 = find(SBE.press_Pa>(median(SBE.press_Pa(round(0.25*end:0.75*end)))...
            -std(SBE.press_Pa(round(0.25*end:0.75*end)))));
        time_start=SBE.mtime(indx3(1));
        time_end=SBE.mtime(indx3(end));
    end
    
    indx3 = SBE.mtime > time_start & SBE.mtime < time_end;

    % make time stamp the same as raw data
    mtime=SBE.mtime(indx3);
%     mtime=time_start:SBE.dt_sec/24/3600:time_end;
    dt = mtime(2)-mtime(1); % data time step (days)
    
    % always use nearest interp for raw data
    press_Pa = SBE.press_Pa(indx3);
    
    Temp = SBE.temp(indx3);
    
    % remove outlyers
    indx = press_Pa < nanmedian(press_Pa)-3*nanstd(press_Pa) |...
    press_Pa > nanmedian(press_Pa)+3*nanstd(press_Pa);
    press_Pa(indx)=NaN;
    % remove negative values
    press_Pa(press_Pa<0)=nan;
    press_Pa = naninterp(press_Pa);
    
    
    % find depth
    [~,sigma] = swstate(S,Temp,nanmean(press_Pa)*1E-4);
    rho = 1000+sigma;
    depth = press_Pa./(g*rho)+gauge_ht;
    Depth = nanmean(depth);
    
    %% filter data
    dt_filt = filter_time/60/24/2;
    mtime_filt = time_start:dt_filt:time_end;
    
    % low pass filter
    [pressure_filt,Fourier.pressure,Fourier.s_vel] = low_pass_filter(naninterp(press_Pa'),dt*24*3600,filter_time*60);
    [depth_filt,Fourier.depth,~] = low_pass_filter(naninterp(depth'),dt*24*3600,filter_time*60);
    
    depth_filt = interp1(mtime,depth_filt,mtime_filt,'linear');
    pressure_filt = interp1(mtime,pressure_filt,mtime_filt,'linear');
    
    %% tidal analysis
    eta = depth-nanmean(depth);
    eta_filt = depth_filt-nanmean(depth_filt);

[TIDES.nameu,TIDES.fu,TIDES.tidecon,eta_tides]=...
    t_tide(eta_filt,'interval',24*dt_filt); 

    eta_notides = eta_filt-eta_tides;    
    
    %% Process Wave Data
if Waves
    if WavesBurst        
                fs = 1./SBE.wave.sample_rate(1);
                
                % remove outlyers
                indx = SBE.wave.press_Pa < nanmedian(SBE.wave.press_Pa)-3*nanstd(SBE.wave.press_Pa) |...
                SBE.wave.press_Pa > nanmedian(SBE.wave.press_Pa)+3*nanstd(SBE.wave.press_Pa);
                SBE.wave.press_Pa(indx)=1;%NaN;
%                 SBE.wave.press_Pa = naninterp( SBE.wave.press_Pa);

                doffu = gauge_ht;
                doffp = gauge_ht;

                indx2 = SBE.wave.mtime > mtime(1) & SBE.wave.mtime < mtime(end);
                mtimew=SBE.wave.mtime(indx2)';
                
                indxnan = logical(0*mtimew);
                
         for i=1:(length(mtimew)) 

            indx = find(SBE.wave.mtime==mtimew(i));

            if ~isempty(indx)
            P = SBE.wave.press_Pa(indx,:)*1E-4; % pressure is in dbar    
            U = P/100;
            V = 0*P;
            
            if min(P)<2E-4
                indxnan(i)=1;
            end
                

            dirmethod=1;
            
            [WaveStats] = wave_stats_spectra(U,V,P,nfft,doffu,doffp,fs,fcutoff,nanmean(rho),dirmethod);

            WaveData.depth(i) = WaveStats.depth;
            WaveData.Hsig_ss(i) = WaveStats.Hsig_ss;
            WaveData.Hsig_ig(i) = WaveStats.Hsig_ig;
            WaveData.HSIG(i,:) = WaveStats.Hsigt;

            WaveData.Hrms_ss(i) = WaveStats.Hrms_ss;
            WaveData.Hrms_ig(i) = WaveStats.Hrms_ig;
            WaveData.Hrms_all(i) = WaveStats.Hrms_all;
            WaveData.HRMS(i,:) = WaveStats.Hrmst;

            WaveData.Tm_ss(i) = WaveStats.Tm_ss;
            WaveData.Tm_ig(i) = WaveStats.Tm_ig;
            WaveData.Tm_all(i) = WaveStats.Tm_all;

            WaveData.Tp_ss(i) = WaveStats.Tp_ss;
            WaveData.Tp_ig(i) = WaveStats.Tp_ig;
            WaveData.Tp_all(i) = WaveStats.Tp_all;

            WaveData.Eflux_ss(i,:) = WaveStats.Eflux_ss';
            
            WaveData.SSE(i,:) = WaveStats.SSEt;
            end
         end
          WaveData.fmt = WaveStats.fmt;
         WaveData.mtime = mtimew;
         WaveData.nfft = nfft;
         WaveData.doffp = doffp;
         WaveData.doffu = doffu;
         WaveData.fs = fs;
         WaveData.fcutoff = fcutoff;
         WaveData.df = WaveStats.df;
         WaveData.num_avg = WaveStats.num_avg;

         clear WaveStats
        % nan out areas with no results 
        WaveData.depth(indxnan) = nan;
        WaveData.Hsig_ss(indxnan) = nan;
        WaveData.Hsig_ig(indxnan) = nan;
        WaveData.HSIG(indxnan,:) = nan;

        WaveData.Hrms_ss(indxnan) = nan;
        WaveData.Hrms_ig(indxnan) = nan;
        WaveData.Hrms_all(indxnan) = nan;
        WaveData.HRMS(indxnan,:) = nan;

        WaveData.Tm_ss(indxnan) = nan;
        WaveData.Tm_ig(indxnan) = nan;
        WaveData.Tm_all(indxnan) = nan;

        WaveData.Tp_ss(indxnan) = nan;
        WaveData.Tp_ig(indxnan) = nan;
        WaveData.Tp_all(indxnan) = nan;

        WaveData.Eflux_ss(indxnan,:) = nan;

        WaveData.SSE(indxnan,:) = nan;

        SBE.wave.press_Pa(SBE.wave.press_Pa==1)=nan;

 
    else
    
   indx = SBE.mtime_wave>time_start & SBE.mtime_wave<time_end;
   WaveData.Hsig = SBE.Hsig(indx);
   WaveData.Tm = SBE.Tsig(indx);
   WaveData.SSE = SBE.SSE(:,indx)';
   WaveData.fmt = SBE.E_bins_f;
   WaveData.mtime = SBE.mtime_wave(indx);
   
   % separate out ig and swell waves
   WaveData.Hsig_ss = WaveData.Hsig.*sum(WaveData.SSE(:,2:end),2)'./sum(WaveData.SSE(:,:),2)';
   WaveData.Hsig_ig = WaveData.Hsig.*sum(WaveData.SSE(:,1),2)'./sum(WaveData.SSE(:,:),2)';
   
   for i=1:length(WaveData.mtime)
       fcentroid_swell = nansum ( WaveData.fmt(2:end).* WaveData.SSE(i,2:end) ) / nansum ( WaveData.SSE(i,2:end) ) ;
       WaveData.Tm_ss(i) = 1/fcentroid_swell;
   end
   
   WaveData.Tm_ig = WaveData.Tm;
   WaveData.Tm_ig(WaveData.Tm_ig<22) = nan;
  
    end
end
    
clear WaveStats doffp doffu fs bin Error mtimew
clear U P V up vp wp u v w
clear ii indx WAV_files indx3 i ig iprocess C C2

save Processed_SBE26_data

end
end

