% function [] = rbr1050_process(gauge_ht,filter_time,Waves,nfft,time_start,time_end)% 
% 
% Process RBR pressure data
% Justin Rogers, Stanford EFML, September 2013
%
% This script loads .mat or .txt files generated by RBR pressure loggers
%
% input:
% gauge height = height of pressure sensor above bottom
% filter_time = time in minutes for desired low pass filtering
% Waves, if 1, process waves, if 0, no processing
% nfft = number of data points to use for wave averaging
% time_start = optional time to begin processing
% time_end = optional time to end processing
%

%%
function [] = rbr1050_process(gauge_ht,filter_time,P_atm,Waves,nfft,fcutoff,...
    time_start,time_end)
g=9.81;
T=29.04;
S=34.6;

MAT_files=dir('RBR*.mat');
TXT_files=dir('RBR*.txt');

for ii=1:max([length(MAT_files),length(TXT_files)])
    
    if ~isempty(MAT_files) % if mat file
        
        load(MAT_files(ii).name)
        starttime=datenum(RBR.starttime,'dd/mm/yyyy HH:MM:SS PM');
        RBR.mtime=starttime+RBR.sampleperiod/3600/24*(0:1:size(RBR.data,1)-1);
        RBR.dt_sec = RBR.sampleperiod;
        RBR.pressure = RBR.data(:,1)';
    end
    
    if ~isempty(TXT_files) % if txt file
        
        headerlines=143;
        filename=TXT_files(ii).name;
        DATA = importdata(filename,' ',headerlines);
        RBR.header_info=DATA.textdata(1:headerlines,1);
        RBR.pressure = DATA.data(:,1)';

        j=1; sec=[];% find sample period
        while isempty(sec)
            [sec] = sscanf(RBR.header_info{j},'LoggingSamplingPeriod=%f:%f:%f');
            j=j+1;
        end
        RBR.dt_sec = sec(1)/3600+sec(2)/60+sec(3);
        
        % find mtime
        RBR.time_start = datenum([DATA.textdata{headerlines+1,1} ' ' DATA.textdata{headerlines+1,2}],01);
        RBR.time_end = datenum([DATA.textdata{end,1} ' ' DATA.textdata{end,2}],01);
        RBR.mtime = linspace(RBR.time_start,RBR.time_end,length(RBR.pressure));
         
    end
    
    clear MAT_files TXT_files DATA sec j jj press_Pa headerlines
%% process data

    if isempty(P_atm) % if no manually defined atmospheric P
    % find avg atmospheric pressure within expected range 
    % (31.99 and 25.69)inHg = (108318, 86986) Pa
    %     indx = RBR.press_Pa_total < 108318 & RBR.press_Pa_total > 86986;
        indx = 1E4*RBR.pressure < 1.3E5 & 1E4*RBR.pressure > 86986;    
        P_atm = 1E4*nanmedian(RBR.pressure(indx));
        if isempty(P_atm) || isnan(P_atm)
           P_atm = 1.01324997E5;
        end
    end   
    
    % find normalized pressure
    RBR.press_Pa = 1E4*RBR.pressure-P_atm;
    
    % find pressures outside 1 std of middle 1/2 of data set
    if isempty(time_start) % if no manual trim defined
    indx3 = find(RBR.press_Pa>(median(RBR.press_Pa(round(0.25*end:0.75*end)))...
        -std(RBR.press_Pa(round(0.25*end:0.75*end)))));
    time_start=RBR.mtime(indx3(1));
    time_end=RBR.mtime(indx3(end));
    end

    % RBR time is not always constant spacing
    mtime=time_start:RBR.dt_sec/24/3600:time_end;
    dt = mtime(2)-mtime(1); % data time step (days)
    
    % always use nearest interp for raw data
    press_Pa = interp1(RBR.mtime,RBR.press_Pa,mtime,'nearest',NaN);
    
    % remove outlyers
    indx = press_Pa < nanmedian(press_Pa)-8*nanstd(press_Pa) |...
    press_Pa > nanmedian(press_Pa)+8*nanstd(press_Pa);
    press_Pa(indx)=NaN;
    press_Pa = naninterp(press_Pa);
    
    % find depth
    [~,sigma] = swstate(S,T,nanmean(press_Pa)*1E-4);
    rho = 1000+sigma;
    depth = press_Pa/(g*rho)+gauge_ht;
    Depth = nanmean(depth);
    
    %% filter data
    dt_filt = filter_time/60/24/2;
    mtime_filt = time_start:dt_filt:time_end;
    
    % low pass filter
    [pressure_filt,Fourier.pressure,Fourier.s_vel] = low_pass_filter(naninterp(press_Pa'),dt*24*3600,filter_time*60);
    [depth_filt,Fourier.depth,~] = low_pass_filter(naninterp(depth'),dt*24*3600,filter_time*60);
    
    depth_filt = interp1(mtime,depth_filt,mtime_filt,'linear');
    pressure_filt = interp1(mtime,pressure_filt,mtime_filt,'linear');
    
    %% tidal analysis
    eta = depth-nanmean(depth);
    eta_filt = depth_filt-nanmean(depth_filt);

[TIDES.nameu,TIDES.fu,TIDES.tidecon,eta_tides]=...
    t_tide(eta_filt,'interval',24*dt_filt); 

    eta_notides = eta_filt-eta_tides;    
    
    %% Process Wave Data
clear WaveData
if Waves

dt_sec = dt*24*3600;
doffu = gauge_ht;
doffp = gauge_ht;
Uw = press_Pa/100;% use dummy values for direction
Vw = 0*Uw;
dirmethod = 1;
  

fs = 1./dt_sec;
dt_big_day = 1/24/60*(filter_time);
    
 for i=1:(length(mtime_filt)-2) % only process points with full time series
    tdown = mtime_filt(i+1)-dt_big_day/2;
    tup = mtime_filt(i+1)+dt_big_day/2;
    indx = find(mtime>tdown & mtime<=tup);
        
    if ~isempty(indx)
    U = Uw(indx);
    V = Vw(indx);
    P = press_Pa(indx)*1E-4; % pressure is in dbar

    [WaveStats] = wave_stats_spectra(U,V,P,nfft,doffu,doffp,fs,fcutoff,rho,dirmethod);

    WaveData.depth(i) = WaveStats.depth;
    WaveData.Hsig_ss(i) = WaveStats.Hsig_ss;
    WaveData.Hsig_ig(i) = WaveStats.Hsig_ig;
    WaveData.HSIG(i,:) = WaveStats.Hsigt;
    
    WaveData.Hrms_ss(i) = WaveStats.Hrms_ss;
    WaveData.Hrms_ig(i) = WaveStats.Hrms_ig;
    WaveData.Hrms_all(i) = WaveStats.Hrms_all;
    WaveData.HRMS(i,:) = WaveStats.Hrmst;
    
    WaveData.Tm_ss(i) = WaveStats.Tm_ss;
    WaveData.Tm_ig(i) = WaveStats.Tm_ig;
    WaveData.Tm_all(i) = WaveStats.Tm_all;
    
    WaveData.Tp_ss(i) = WaveStats.Tp_ss;
    WaveData.Tp_ig(i) = WaveStats.Tp_ig;
    WaveData.Tp_all(i) = WaveStats.Tp_all;
        
    WaveData.Eflux_ss(i,:) = WaveStats.Eflux_ss';
    WaveData.ztest_ss(i) = WaveStats.ztest_ss;
    WaveData.Cpu_ss(i) = WaveStats.Cpu_ss;
    
%     if dirmethod==1
%     WaveData.dir_ss(i) = WaveStats.dir_ss1;
%     WaveData.dir_ig(i) = WaveStats.dir_ig1;
%     WaveData.DIR(i,:) = WaveStats.dirt(1,:);
%     else
%     WaveData.dir_ss(i) = WaveStats.dir_ss2;
%     WaveData.dir_ig(i) = WaveStats.dir_ig2;
%     WaveData.DIR(i,:) = WaveStats.dirt(2,:);
%     end
    
%     WaveData.spread_ss(i) = WaveStats.spread_ss2;
%     WaveData.spread_ig(i) = WaveStats.spread_ig2;
%     WaveData.SPREAD(i,:) = WaveStats.spreadt(2,:);
%     
    WaveData.Eflux_ig(i,:) = WaveStats.Eflux_ig';
    
%     WaveData.Sxx_ss(i) = WaveStats.Sxx_ss;
%     WaveData.Sxy_ss(i) = WaveStats.Sxy_ss;
%     WaveData.Syy_ss(i) = WaveStats.Syy_ss;
%     
%     WaveData.SUU(i,:) = WaveStats.Suut;
%     WaveData.SUV(i,:) = WaveStats.Suvt;
%     WaveData.SVV(i,:) = WaveStats.Svvt;
    WaveData.SSE(i,:) = WaveStats.SSEt;
    
    WaveData.USt(i,:) = WaveStats.Ust;
%     WaveData.VSt(i,:) = WaveStats.Vst;
    WaveData.Us(i) = WaveStats.Us;
%     WaveData.Vs(i) = WaveStats.Vs;
    end
    
 end
 WaveData.fmt = WaveStats.fmt;
 WaveData.Tt = WaveStats.Tt;
 WaveData.mtime = mtime_filt(2:end-1);
 WaveData.nfft = nfft;
 WaveData.doffp = doffp;
 WaveData.doffu = doffu;
 WaveData.fs = fs;
 WaveData.fcutoff = fcutoff;
 WaveData.df = WaveStats.df;
 WaveData.num_avg = WaveStats.num_avg;
 clear ii WaveStats doffp doffu fs fcutoff bin Error U P V


    end
clear ii indx

save Processed_RBR1050_data

end
end

